/**
 * 
 */
package de.lmu.ifi.dbs.knowing.core.processing;

import weka.core.Instances;

/**
 * @author Nepomuk Seiler
 * @version 0.1
 */
public interface IResultProcessor extends IProcessor {

	/**
	 * <p>This method should never called directly.<br>
	 * It should only be used by IPresenter to obtain <br>
	 * the results generated by the IResultProcessor.</p>
	 * 
	 * @return created results
	 */
	Instances getResult();
}
